# Generated by Django 4.1.3 on 2022-11-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='date',
        ),
    ]
