# Generated by Django 3.2.5 on 2022-12-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20221214_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='not exist', unique=True),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='subscriberscategory',
            constraint=models.UniqueConstraint(fields=('subscriber', 'category'), name='unique_subscription_user_cat'),
        ),
    ]
